"""Thin wrapper over vendor/TE_model/pipeline.bash (module_contracts §M3).

Full contract: docs/te_model_contract.md §5 and plan L2.
- Stage 0 via generated trials/{study}/config.py calling main()
  with custom_experiment_list (bypasses paxdb_filtered_sample.csv).
- Stage 1-3 via `bash pipeline.bash -t {study}` (cwd=vendor/TE_model).
- Product rename: human_* -> {organism}_* into <out-dir>/.

CLI: python -m te_analysis.run_downstream --study-dir PATH --out-dir PATH
"""
from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path
from textwrap import dedent

import pandas as pd

from te_analysis.config import REPO_ROOT

VENDOR_TE_MODEL = REPO_ROOT / "vendor" / "TE_model"
TE_MODEL_TRIALS = VENDOR_TE_MODEL / "trials"
METADATA_DEFAULT = REPO_ROOT / "data" / "raw" / "metadata.csv"
PRODUCTS = ("human_TE_cellline_all.csv", "human_TE_cellline_all_T.csv",
            "human_TE_sample_level.rda")


def _load(metadata: Path, study: str) -> tuple[list[str], str]:
    if not metadata.is_file():
        raise FileNotFoundError(f"metadata.csv not found: {metadata}")
    df = pd.read_csv(metadata, header=1, dtype=str, keep_default_na=False)
    sub = df[df["study_name"] == study.split("_", 1)[0]]
    if sub.empty:
        raise ValueError(f"study {study!r} not in metadata.csv")
    orgs = {o for o in sub["organism"] if o}
    if len(orgs) != 1:
        raise ValueError(f"expected 1 organism, got {orgs}")
    return sorted({e for e in sub["experiment_alias"] if e}), orgs.pop()


def _write_trial(trial_dir: Path, experiments: list[str]) -> None:
    trial_dir.mkdir(parents=True, exist_ok=True)
    (trial_dir / "__init__.py").write_text("")
    (trial_dir / "config.py").write_text(dedent(f'''\
        """Auto-generated by te_analysis.run_downstream (L2)."""
        import os
        from src.ribo_counts_to_csv import main
        main(workdir=os.path.dirname(os.path.realpath(__file__)),
             sample_filter=lambda df: df, ribo_dedup=False, rna_seq_dedup=False,
             custom_experiment_list={experiments!r})
    '''))


def _copy_products(trial_dir: Path, out_dir: Path, organism: str) -> int:
    out_dir.mkdir(parents=True, exist_ok=True)
    org = organism.strip().lower().replace(" ", "_")
    n = 0
    for name in PRODUCTS:
        src = trial_dir / name
        if src.is_file():
            shutil.copy2(src, out_dir / name.replace("human_", f"{org}_"))
            n += 1
    return n


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--study-dir", type=Path, required=True)
    ap.add_argument("--out-dir", type=Path, required=True)
    ap.add_argument("--metadata", type=Path, default=METADATA_DEFAULT)
    args = ap.parse_args(argv)
    if not args.study_dir.is_dir():
        raise FileNotFoundError(f"--study-dir not a directory: {args.study_dir}")
    study = args.study_dir.name
    experiments, organism = _load(args.metadata, study)
    print(f"[run_downstream] {study} organism={organism} N={len(experiments)}")
    trial_dir = TE_MODEL_TRIALS / study
    _write_trial(trial_dir, experiments)
    cmd = ["bash", "pipeline.bash", "-t", study]
    print(f"[run_downstream] {' '.join(cmd)}  (cwd={VENDOR_TE_MODEL})")
    rc = subprocess.run(cmd, cwd=VENDOR_TE_MODEL, check=False).returncode
    if rc != 0:
        return rc
    n = _copy_products(trial_dir, args.out_dir, organism)
    print(f"[run_downstream] copied {n} product file(s) -> {args.out_dir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
